[theme]
primaryColor="#3b82f6"
backgroundColor="#0a0a0a"
secondaryBackgroundColor="#1e1e2e"
textColor="#cbd5e1"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"
